name: holligan_202403
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - expat=2.5.0
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.12.2
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - attrs==23.2.0
    - black==24.3.0
    - cfgv==3.4.0
    - click==8.1.7
    - contourpy==1.2.0
    - cycler==0.12.1
    - distlib==0.3.8
    - filelock==3.13.3
    - fonttools==4.50.0
    - future==1.0.0
    - hepunits==2.3.3
    - identify==2.5.35
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - matplotlib==3.8.3
    - mypy-extensions==1.0.0
    - nodeenv==1.8.0
    - numpy==1.26.4
    - packaging==24.0
    - pandas==2.2.1
    - particle==0.23.1
    - pathspec==0.12.1
    - pillow==10.2.0
    - platformdirs==4.2.0
    - pre-commit==3.7.0
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - pyyaml==6.0.1
    - scipy==1.12.0
    - six==1.16.0
    - snakefmt==0.10.0
    - toml==0.10.2
    - typing-extensions==4.10.0
    - tzdata==2024.1
    - uncertainties==3.1.7
    - virtualenv==20.25.1
